name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - seaborn
  - dask
  - bqplot
  - ipywidgets
  - pip
  - pip:
    - sklearn
    - scipy
    - statsmodel
